### ISSUE TITLE
Error 400 thrown for 

### ISSUE THREAD

**Issue by ignasdamunskis** [bpolaszek/webpush-bundle#48]
First of all, very good package, love it! I use version 0.9 since my PHP is version 7.4.

Most of the times it works as expected. Push notifications to Android Chrome and iOS Safari are sending without any issues, I had some issues with Android Firefox, it was throwing 413, but resolved decreasing the max padding length to 2847.

The issue I don't know how to resolve is sending push notifications to my clients using Windows devices, I always get an ERROR 400 for endpoints: `https://wns2-par02p.notify.windows.com/w/?token=...`

I usualy log the notification errors as it happens, but since PushResponse class has no message property I can't properly debug the issue. Anyone else facing the issue, or knows how o resolve it?

**Comment by bbehrendt-mm** [comment]
Hi! I just had the same problem myself, and found out that Microsoft requires a TTL header to be set when pushing notifications. The easiest way to fix this is by setting a default TTL for the bundle to use inside your services.yaml: 

```yaml
    BenTools\WebPushBundle\Sender\PushMessageSender:
      arguments:
        $defaultOptions:
          TTL: 2419200
```
